export { default as Jumbotron } from './Jumbotron/jumbotron'
export { default as Footer } from './Footer/footer'
export { default as HomeHeader } from './HomeHeader/homeHeader'
export { default as Form } from './Form/form'
export { default as Loading } from './Loading/loading'
export { default as Player } from './Player/player'
export { default as Card } from './Card/card'
